"""
Test: Dynamic Basis SQL Generation against Portfolio NPV and Risk

Demonstrates that we can feed complex swap NPV and Risk symbolic expressions
into the BasisExtractor, generate flat component tuples, and execute them perfectly
in a single static DuckDB query.
"""

import pytest
import duckdb
import pandas as pd
from typing import Dict

from instruments.ir_swap_fixed_floatapprox import IRSwapFixedFloatApprox
from instruments.portfolio import Portfolio
from marketmodel.yield_curve import LinearTermDiscountCurve, YieldCurvePoint
from reactive.basis_extractor import BasisExtractor
from reactive.expr import eval_cached

# ── Fixtures ────────────────────────────────────────────────────────────────

@pytest.fixture
def curve():
    points = [
        YieldCurvePoint(name="1Y", tenor_years=1.0, fitted_rate=0.03, is_fitted=True),
        YieldCurvePoint(name="5Y", tenor_years=5.0, fitted_rate=0.05, is_fitted=True),
        YieldCurvePoint(name="10Y", tenor_years=10.0, fitted_rate=0.07, is_fitted=True),
    ]
    return LinearTermDiscountCurve(name="TEST", points=points)

@pytest.fixture
def portfolio(curve):
    p = Portfolio()
    p.add_instrument("SWAP_3Y", IRSwapFixedFloatApprox(
        notional=30_000_000, fixed_rate=0.04, tenor_years=3.0, curve=curve,
    ))
    p.add_instrument("SWAP_5Y", IRSwapFixedFloatApprox(
        notional=50_000_000, fixed_rate=0.05, tenor_years=5.0, curve=curve,
    ))
    p.add_instrument("SWAP_10Y", IRSwapFixedFloatApprox(
        notional=80_000_000, fixed_rate=0.07, tenor_years=10.0, curve=curve,
    ))
    return p

# ── Dynamic DB Test ────────────────────────────────────────────────────────

def test_portfolio_skinny_components_matches(portfolio, curve):
    ctx_base = portfolio.pillar_context()
    
    # 1. Native Python Evaluated Values
    py_npvs = portfolio.eval_npvs(ctx_base)
    py_jac = portfolio.eval_instrument_risk(ctx_base)

    # 2. Extract into Flat Table Shape
    extractor = BasisExtractor()
    components_list = portfolio.to_skinny_components(extractor)
    
    # Pad out None on components dictionary for pandas frame consistency
    max_vars = max((bf.num_vars for bf in extractor.registry.values()), default=1)
    max_params = max((bf.num_params for bf in extractor.registry.values()), default=1)
    for c in components_list:
        for i in range(1, max_vars + 1):
            if f"X{i}" not in c:
                c[f"X{i}"] = None
        for i in range(1, max_params + 1):
            if f"p{i}" not in c:
                c[f"p{i}"] = 0.0
                
    # 3. Build Scenarios Table
    # A scenario table requires Scenario_Id, Knot_Id, Knot_Value
    # We will test Scenario 0 = original rates, Scenario 1 = shifted
    scenarios = []
    
    # Scenario 0
    for knot in ["1Y", "5Y", "10Y"]:
        scenarios.append({
            "Scenario_Id": 0,
            "Knot_Id": knot,
            "Knot_Value": ctx_base[knot]
        })
        
    # Scenario 1 (parallel 1bp shift)
    ctx_shift = {k: v + 0.0001 for k, v in ctx_base.items()}
    for knot in ["1Y", "5Y", "10Y"]:
        scenarios.append({
            "Scenario_Id": 1,
            "Knot_Id": knot,
            "Knot_Value": ctx_shift[knot]
        })

    # 4. Fire Into DuckDB
    con = duckdb.connect()
    
    df_components = pd.DataFrame(components_list)
    df_scenarios = pd.DataFrame(scenarios)
    
    con.execute("CREATE TABLE t_components AS SELECT * FROM df_components")
    con.execute("CREATE TABLE t_scenarios AS SELECT * FROM df_scenarios")
    
    # Get that skinny SQL generated by Portfolio automatically
    sql = portfolio.to_skinny_sql_query(extractor)
    
    # Run in DuckDB Vector Engine!
    res = con.execute(sql).df()

    # 5. Math Check Scenario 0 equals original Python Output
    scen_0 = res[res['Scenario_Id'] == 0]
    assert len(scen_0) == 3, "Should return exactly 3 grouped swaps"
    
    for _, row in scen_0.iterrows():
        swap_id = row['Swap_Id']
        # NPV check
        assert py_npvs[swap_id] == pytest.approx(row['NPV'], rel=1e-10)
        
        # Risk Jacobian column check
        for pillar in ["1Y", "5Y", "10Y"]:
            col_name = f"dNPV_d{pillar}"
            if col_name in row and pillar in py_jac.get(swap_id, {}):
                expected = py_jac[swap_id].get(pillar, 0.0)
                actual = row[col_name]
                assert expected == pytest.approx(actual, rel=1e-8)

    # 6. Math Check Scenario 1 equals shifted Python output
    scen_1 = res[res['Scenario_Id'] == 1]
    py_npvs_shift = portfolio.eval_npvs(ctx_shift)
    
    for _, row in scen_1.iterrows():
        swap_id = row['Swap_Id']
        assert py_npvs_shift[swap_id] == pytest.approx(row['NPV'], rel=1e-10)
    
    con.close()


def test_python_compiled_basis_matches(portfolio, curve):
    """Python compiled basis functions produce the same values as native eval."""
    ctx_base = portfolio.pillar_context()
    
    # Native Python reference
    py_npvs = portfolio.eval_npvs(ctx_base)
    py_jac = portfolio.eval_instrument_risk(ctx_base)
    
    # Extract and evaluate via compiled basis functions
    extractor = BasisExtractor()
    components_list = portfolio.to_skinny_components(extractor)
    
    # Build type lookup
    type_lookup = {}
    for bf in extractor.registry.values():
        type_lookup[bf.component_type] = bf
    
    # Evaluate each component
    results = {}  # (Swap_Id, Component_Class) → sum
    for comp in components_list:
        swap_id = comp["Swap_Id"]
        comp_class = comp["Component_Class"]
        bf = type_lookup[comp["Component_Type"]]
        
        # Build knot values
        knots = []
        for j in range(1, bf.num_vars + 1):
            x_name = comp.get(f"X{j}")
            knots.append(ctx_base.get(x_name, 0.0) if x_name else 0.0)
        
        # Build params
        params = [comp.get(f"p{j+1}", 0.0) for j in range(bf.num_params)]
        
        value = extractor.evaluate_component(bf.component_type, params, knots)
        
        key = (swap_id, comp_class)
        results[key] = results.get(key, 0.0) + comp["Weight"] * value
    
    # Verify NPVs match
    for name, expected in py_npvs.items():
        actual = results.get((name, "NPV"), 0.0)
        assert expected == pytest.approx(actual, rel=1e-10), \
            f"NPV mismatch for {name}: expected={expected}, basis={actual}"
    
    # Verify Jacobian matches
    for name, row in py_jac.items():
        for pillar, expected in row.items():
            col_key = f"dNPV_d{pillar}"
            actual = results.get((name, col_key), 0.0)
            if abs(expected) < 1e-15:
                assert abs(actual) < 1e-10
            else:
                assert expected == pytest.approx(actual, rel=1e-8), \
                    f"Jacobian mismatch for {name}/{pillar}: expected={expected}, basis={actual}"


def test_numpy_vectorized_basis_matches(portfolio, curve):
    """NumPy vectorized evaluation matches native eval."""
    import numpy as np
    
    ctx_base = portfolio.pillar_context()
    py_npvs = portfolio.eval_npvs(ctx_base)
    
    extractor = BasisExtractor()
    components_list = portfolio.to_skinny_components(extractor)
    
    max_vars = max((bf.num_vars for bf in extractor.registry.values()), default=1)
    max_params = max((bf.num_params for bf in extractor.registry.values()), default=1)
    
    # Pad and build arrays
    for c in components_list:
        for i in range(1, max_vars + 1):
            if f"X{i}" not in c: c[f"X{i}"] = None
        for i in range(1, max_params + 1):
            if f"p{i}" not in c: c[f"p{i}"] = 0.0
    
    swap_ids = [c["Swap_Id"] for c in components_list]
    comp_classes = [c["Component_Class"] for c in components_list]
    comp_types = np.array([c["Component_Type"] for c in components_list])
    weights = np.array([c["Weight"] for c in components_list])
    
    param_arr = np.zeros((len(components_list), max_params))
    var_arr = np.zeros((len(components_list), max_vars))
    
    for idx, comp in enumerate(components_list):
        for j in range(max_params):
            param_arr[idx, j] = comp.get(f"p{j+1}", 0.0)
        for j in range(max_vars):
            x_name = comp.get(f"X{j+1}")
            var_arr[idx, j] = ctx_base.get(x_name, 0.0) if x_name else 0.0
    
    # Vectorized evaluation by basis type
    result = np.zeros(len(components_list))
    for bf in extractor.registry.values():
        mask = comp_types == bf.component_type
        if not np.any(mask):
            continue
        p = param_arr[mask]
        x = var_arr[mask]
        py_code = bf.dh_template.replace("Math.pow", "np.power").replace("Math.", "np.")
        local_ns = {"np": np}
        for j in range(bf.num_params):
            local_ns[f"p{j+1}"] = p[:, j]
        for j in range(bf.num_vars):
            local_ns[f"X{j+1}"] = x[:, j]
        compiled = compile(py_code, f"<numpy_basis_{bf.component_type}>", "eval")
        result[mask] = eval(compiled, local_ns)
    
    weighted = weights * result
    
    # Aggregate NPVs
    npv_totals = {}
    for i, (swap_id, comp_class) in enumerate(zip(swap_ids, comp_classes)):
        if comp_class == "NPV":
            npv_totals[swap_id] = npv_totals.get(swap_id, 0.0) + weighted[i]
    
    for name, expected in py_npvs.items():
        actual = npv_totals.get(name, 0.0)
        assert expected == pytest.approx(actual, rel=1e-10), \
            f"NumPy NPV mismatch for {name}: expected={expected}, numpy={actual}"


def test_basis_type_count_is_minimal(portfolio, curve):
    """With proper constant distribution, basis types should be small."""
    extractor = BasisExtractor()
    portfolio.to_skinny_components(extractor)
    
    # With 3 pillars and proper extraction, we expect a small number of types
    assert len(extractor.registry) <= 15, \
        f"Too many basis types ({len(extractor.registry)}): constant distribution may not be working"
    
    # Max params per type should be reasonable (not 100+)
    max_params = max(bf.num_params for bf in extractor.registry.values())
    assert max_params <= 12, \
        f"Max params per basis ({max_params}) too high — extraction not distributing constants"


def test_all_engines_agree_on_npvs(portfolio, curve):
    """Cross-validate: Python eval, compiled basis, DuckDB SQL all agree on NPVs."""
    ctx_base = portfolio.pillar_context()
    
    # 1. Native Python
    py_npvs = portfolio.eval_npvs(ctx_base)
    
    # 2. Compiled basis
    extractor = BasisExtractor()
    components_list = portfolio.to_skinny_components(extractor)
    
    type_lookup = {bf.component_type: bf for bf in extractor.registry.values()}
    basis_npvs = {}
    for comp in components_list:
        if comp["Component_Class"] != "NPV":
            continue
        bf = type_lookup[comp["Component_Type"]]
        knots = []
        for j in range(1, bf.num_vars + 1):
            x_name = comp.get(f"X{j}")
            knots.append(ctx_base.get(x_name, 0.0) if x_name else 0.0)
        params = [comp.get(f"p{j+1}", 0.0) for j in range(bf.num_params)]
        value = extractor.evaluate_component(bf.component_type, params, knots)
        basis_npvs[comp["Swap_Id"]] = basis_npvs.get(comp["Swap_Id"], 0.0) + comp["Weight"] * value
    
    # 3. DuckDB SQL
    max_vars = max((bf.num_vars for bf in extractor.registry.values()), default=1)
    max_params = max((bf.num_params for bf in extractor.registry.values()), default=1)
    for c in components_list:
        for i in range(1, max_vars + 1):
            if f"X{i}" not in c: c[f"X{i}"] = None
        for i in range(1, max_params + 1):
            if f"p{i}" not in c: c[f"p{i}"] = 0.0
    
    con = duckdb.connect()
    df_components = pd.DataFrame(components_list)
    con.execute("CREATE TABLE t_components AS SELECT * FROM df_components")
    
    scenarios = [{"Scenario_Id": 0, "Knot_Id": k, "Knot_Value": v} for k, v in ctx_base.items()]
    df_scenarios = pd.DataFrame(scenarios)
    con.execute("CREATE TABLE t_scenarios AS SELECT * FROM df_scenarios")
    
    sql = portfolio.to_skinny_sql_query(extractor)
    sql_result = con.execute(sql).fetchdf()
    con.close()
    
    sql_npvs = {}
    for _, row in sql_result.iterrows():
        sql_npvs[row["Swap_Id"]] = row["NPV"]
    
    # All three must agree
    for name in py_npvs:
        py_val = py_npvs[name]
        basis_val = basis_npvs.get(name, 0.0)
        sql_val = sql_npvs.get(name, 0.0)
        
        assert py_val == pytest.approx(basis_val, rel=1e-10), \
            f"{name}: Python ({py_val}) != Basis ({basis_val})"
        assert py_val == pytest.approx(sql_val, rel=1e-10), \
            f"{name}: Python ({py_val}) != SQL ({sql_val})"
